name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests
    env:
      DATABRICKS_AUTH_TYPE: oauth-m2m
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Run unit tests
        run: databricks bundle run -- uv run pytest

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to dev
    needs: test
    environment: Dev
    env:
      DATABRICKS_AUTH_TYPE: oauth-m2m
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Deploy bundle
        run: databricks bundle deploy --target dev
